doc revert reason
ConsenSys/doc.goquorum pull request #118
Opened 2021-08-04 22:54 UTC by rolandtyler

## Pull Request Description
Documented revertreason CLI option and added revertreason concept page

## Fixed Issue(s)

fixes #111

2021-08-05 06:49 UTC, alexandratran requested changes
Great first issue! Minor change request.

2021-08-05 06:49 UTC, alexandratran commented on docs/HowTo/Use/Revert-Reason.md
> +[`eth_getTransactionReceipt`](https://eth.wiki/json-rpc/API#eth_getTransactionReceipt) includes
```suggestion
[`eth_getTransactionReceipt`](https://eth.wiki/json-rpc/API#eth_gettransactionreceipt) includes
```

Sorry we didn't catch this before, but headers in URLs need to be lowercase to work.

2021-08-05 06:49 UTC, alexandratran commented on docs/Reference/CLI-Syntax.md
> +[`eth_getTransactionReceipt`](https://eth.wiki/json-rpc/API#eth_getTransactionReceipt) response.
```suggestion
[`eth_getTransactionReceipt`](https://eth.wiki/json-rpc/API#eth_gettransactionreceipt) response.
```

Same as previous comment.

2021-08-05 18:44 UTC, alexandratran approved these changes
LGTM.

2021-08-10 07:53 UTC, ricardolyn approved these changes

2021-08-10 14:13 UTC, merged